# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appTitle = QtWidgets.QLabel(self.centralwidget)
        self.appTitle.setObjectName("appTitle")
        self.appTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.appTitle)
        
        self.horizontal = QtWidgets.QHBoxLayout()
        self.horizontal.setObjectName("horizontal")
        self.womenMenu = QtWidgets.QToolButton(self.centralwidget)
        self.womenMenu.setObjectName("womenMenu")
        self.womenMenu.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.womenMenu.setMenu(QtWidgets.QMenu())
        self.horizontal.addWidget(self.womenMenu)
        self.menMenu = QtWidgets.QToolButton(self.centralwidget)
        self.menMenu.setObjectName("menMenu")
        self.menMenu.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.menMenu.setMenu(QtWidgets.QMenu())
        self.horizontal.addWidget(self.menMenu)
        self.verticalLayout.addLayout(self.horizontal)
        
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        
        self.verticalLayout.addWidget(self.stackedWidget)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        #MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.centralwidget.setStyleSheet('''
            QWidget { background: #FFFFFF;}
        ''')
        self.appTitle.setText(_translate("MainWindow", "Find It"))
        self.appTitle.setStyleSheet('''
            QLabel {
                font-family: Andale Mono;
                font-size: 30px;
                word-spacing: 1px;
            }  
            QLabel:hover {
                
            }      
        ''')
        
        # add list of categories for menu
        self.womenMenu.setText(_translate("MainWindow", "Women"))
        self.womenMenu.setStyleSheet('''
            QToolButton {
                border: none;
            }
            QToolButton::menu-indicator { image: none;}
        ''')
        self.menMenu.setText(_translate("MainWindow", "Men"))
        self.menMenu.setStyleSheet('''
            QToolButton {
                border: none;
            }
            QToolButton::menu-indicator { image: none;}
        ''')
        self.back.setText(_translate("MainWindow", "back"))
        self.back.setStyleSheet('''
            QPushButton {
                border: none;
            }
        ''')
        self.next.setText(_translate("MainWindow", "next"))
        self.next.setStyleSheet('''
            QPushButton {
                border: none;
            }
        ''')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
